### ISSUE TITLE
Error while using Helm chart for installation 

### ISSUE THREAD

**Issue by anish97IND** [GoogleCloudPlatform/flink-on-k8s-operator#212] opened 2020-04-06 19:46 UTC
While creating flink operator using helm chart following status comes up for pods.

```
NAMESPACE                NAME                                                       READY   STATUS              RESTARTS   AGE
flink-operator-system2   cert-job-4hfq6                                             0/1     **Error**               0          14s
flink-operator-system2   flink-operator-controller-manager-78b78c46fd-tjg98         0/2     **ContainerCreating**   0          14s
```

when checked in logs using :
`kubectl logs -n flink-operator-system2 -l app=flink-operator --all-containers
`
Above log check shows following error
`Error from server (BadRequest): container "kube-rbac-proxy" in pod "flink-operator-controller-manager-78b78c46fd-tjg98" is waiting to start: ContainerCreating`

**Comment by hongyegong** [comment] 2020-04-06 19:50
Duplicate of #207

**Closed by hongyegong** 2020-04-06 19:50 UTC
