### ISSUE TITLE
How to delete a flinkcluster

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#129] opened 2019-11-21 03:20 UTC
When I Tear down a k8s cluster like 'kubectl delete flinkclusters k8s -n k8sNameSpace',but It only delete from flinkclusters, and the pods ,deployments, services not delete. Is there have any method to delete clear
And I have try this 3 step. It can tear down clear
1.delete flinkclusters  `kubectl delete flinkclusters k8s -n k8sNameSpace`
2.delete deployment 
3.delete services.

as any methed clear by one command. not 'kubectl delete -f **.yaml'

**Comment by Mrart** [comment] 2019-11-21 06:07
2019-11-21T06:03:24.554Z	INFO	controllers.FlinkCluster	---------- 1. Observe the current state ----------	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.554Z	INFO	controllers.FlinkCluster	Observed cluster	{"cluster": "sloth/k8s", "cluster": "nil"}
2019-11-21T06:03:24.554Z	INFO	controllers.FlinkCluster	Observed configMap	{"cluster": "sloth/k8s", "state": {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"k8s-configmap","namespace":"sloth","selfLink":"/api/v1/namespaces/sloth/configmaps/k8s-configmap","uid":"d3fdb1b6-23e6-4691-80f4-c2135590a4bb","resourceVersion":"4770538","creationTimestamp":"2019-11-20T13:24:39Z","labels":{"app":"flink","cluster":"k8s"}},"data":{"flink-conf.yaml":"blob.server.port: 6124\njobmanager.rpc.address: k8s-jobmanager\njobmanager.rpc.port: 6123\nquery.server.port: 6125\nrest.port: 8081\n","log4j-console.properties":"log4j.rootLogger=INFO, console\nlog4j.logger.akka=INFO\nlog4j.logger.org.apache.kafka=INFO\nlog4j.logger.org.apache.hadoop=INFO\nlog4j.logger.org.apache.zookeeper=INFO\nlog4j.appender.console=org.apache.log4j.ConsoleAppender\nlog4j.appender.console.layout=org.apache.log4j.PatternLayout\nlog4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n\nlog4j.logger.org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline=ERROR, console","logback-console.xml":"\u003cconfiguration\u003e\n    \u003cappender name=\"console\" class=\"ch.qos.logback.core.ConsoleAppender\"\u003e\n        \u003cencoder\u003e\n            \u003cpattern\u003e%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{60} %X{sourceThread} - %msg%n\u003c/pattern\u003e\n        \u003c/encoder\u003e\n    \u003c/appender\u003e\n    \u003croot level=\"INFO\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/root\u003e\n    \u003clogger name=\"akka\" level=\"INFO\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/logger\u003e\n    \u003clogger name=\"org.apache.kafka\" level=\"INFO\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/logger\u003e\n    \u003clogger name=\"org.apache.hadoop\" level=\"INFO\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/logger\u003e\n    \u003clogger name=\"org.apache.zookeeper\" level=\"INFO\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/logger\u003e\n    \u003clogger name=\"org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline\" level=\"ERROR\"\u003e\n        \u003cappender-ref ref=\"console\"/\u003e\n    \u003c/logger\u003e\n\u003c/configuration\u003e"}}}
2019-11-21T06:03:24.554Z	INFO	controllers.FlinkCluster	Observed JobManager deployment	{"cluster": "sloth/k8s", "state": {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"k8s-jobmanager","namespace":"sloth","selfLink":"/apis/apps/v1/namespaces/sloth/deployments/k8s-jobmanager","uid":"c0a7b2cd-fb78-4840-9bcd-562a94ab2d0b","resourceVersion":"4776735","generation":1,"creationTimestamp":"2019-11-21T03:27:45Z","labels":{"app":"flink","cluster":"k8s","component":"jobmanager"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flink","cluster":"k8s","component":"jobmanager"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"flink","cluster":"k8s","component":"jobmanager"}},"spec":{"volumes":[{"name":"flink-config-volume","configMap":{"name":"k8s-configmap","defaultMode":420}}],"containers":[{"name":"jobmanager","image":"sloth-test0.dg.163.org/flink/flink:1.8.2","args":["jobmanager"],"ports":[{"name":"rpc","containerPort":6123,"protocol":"TCP"},{"name":"blob","containerPort":6124,"protocol":"TCP"},{"name":"query","containerPort":6125,"protocol":"TCP"},{"name":"ui","containerPort":8081,"protocol":"TCP"}],"env":[{"name":"JOB_MANAGER_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"containerName":"jobmanager","resource":"limits.cpu","divisor":"1m"}}},{"name":"JOB_MANAGER_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"containerName":"jobmanager","resource":"limits.memory","divisor":"1Mi"}}}],"resources":{"limits":{"cpu":"1024m","memory":"1Gi"}},"volumeMounts":[{"name":"flink-config-volume","mountPath":"/opt/flink/conf"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":1,"replicas":1,"updatedReplicas":1,"readyReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2019-11-21T03:27:48Z","lastTransitionTime":"2019-11-21T03:27:48Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2019-11-21T03:27:48Z","lastTransitionTime":"2019-11-21T03:27:45Z","reason":"NewReplicaSetAvailable","message":"ReplicaSet \"k8s-jobmanager-7f6584d6c5\" has successfully progressed."}]}}}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Observed JobManager service	{"cluster": "sloth/k8s", "state": {"kind":"Service","apiVersion":"v1","metadata":{"name":"k8s-jobmanager","namespace":"sloth","selfLink":"/api/v1/namespaces/sloth/services/k8s-jobmanager","uid":"e3741299-b57d-46c8-b9c4-0ff882d1e9ae","resourceVersion":"4776737","creationTimestamp":"2019-11-21T03:27:45Z","labels":{"app":"flink","cluster":"k8s","component":"jobmanager"}},"spec":{"ports":[{"name":"rpc","protocol":"TCP","port":6123,"targetPort":"rpc"},{"name":"blob","protocol":"TCP","port":6124,"targetPort":"blob"},{"name":"query","protocol":"TCP","port":6125,"targetPort":"query"},{"name":"ui","protocol":"TCP","port":8081,"targetPort":"ui"}],"selector":{"app":"flink","cluster":"k8s","component":"jobmanager"},"clusterIP":"10.111.158.126","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Observed JobManager ingress	{"cluster": "sloth/k8s", "state": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Observed TaskManager deployment	{"cluster": "sloth/k8s", "state": {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"k8s-taskmanager","namespace":"sloth","selfLink":"/apis/apps/v1/namespaces/sloth/deployments/k8s-taskmanager","uid":"4f2846c6-3f19-4a2d-b84b-46bc45b8f7c5","resourceVersion":"4776736","generation":1,"creationTimestamp":"2019-11-21T03:27:45Z","labels":{"app":"flink","cluster":"k8s","component":"taskmanager"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flink","cluster":"k8s","component":"taskmanager"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"flink","cluster":"k8s","component":"taskmanager"}},"spec":{"volumes":[{"name":"flink-config-volume","configMap":{"name":"k8s-configmap","defaultMode":420}}],"containers":[{"name":"taskmanager","image":"sloth-test0.dg.163.org/flink/flink:1.8.2","args":["taskmanager"],"ports":[{"name":"data","containerPort":6121,"protocol":"TCP"},{"name":"rpc","containerPort":6122,"protocol":"TCP"},{"name":"query","containerPort":6125,"protocol":"TCP"}],"env":[{"name":"TASK_MANAGER_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"containerName":"taskmanager","resource":"limits.cpu","divisor":"1m"}}},{"name":"TASK_MANAGER_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"containerName":"taskmanager","resource":"limits.memory","divisor":"1Mi"}}}],"resources":{"limits":{"cpu":"1024m","memory":"4Gi"}},"volumeMounts":[{"name":"flink-config-volume","mountPath":"/opt/flink/conf"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":1,"replicas":1,"updatedReplicas":1,"readyReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2019-11-21T03:27:48Z","lastTransitionTime":"2019-11-21T03:27:48Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2019-11-21T03:27:48Z","lastTransitionTime":"2019-11-21T03:27:45Z","reason":"NewReplicaSetAvailable","message":"ReplicaSet \"k8s-taskmanager-774d978b4f\" has successfully progressed."}]}}}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	---------- 2. Update cluster status ----------	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	The cluster has been deleted, no status to update	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	---------- 3. Compute the desired state ----------	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "ConfigMap": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "JobManager deployment": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "JobManager service": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "JobManager ingress": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "TaskManager deployment": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	Desired state	{"cluster": "sloth/k8s", "Job": "nil"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	---------- 4. Take actions ----------	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.555Z	INFO	controllers.FlinkCluster	The cluster has been deleted, no action to take	{"cluster": "sloth/k8s"}
2019-11-21T06:03:24.555Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "flinkcluster", "request": "sloth/k8s"}

**Comment by Mrart** [comment] 2019-11-21 06:08
See the logs, It seems a bug. It desired nil. but when The cluster is deleted, It don't delet other resouces

**Comment by functicons** [comment] 2019-11-21 21:16
Thanks for the report, but I couldn't reproduce your problem. After you run `kubectl delete flinkclusters <name> -n <namespace>`, all child resources (JM/TM deployments, service, configmap, etc) should be automatically deleted, because we have `ownerReferences` of the child resources to the flink cluster, e.g.:

```
$ kubectl get deployments flinkjobcluster-sample-jobmanager -n dagang -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
  ...
  name: flinkjobcluster-sample-jobmanager
  namespace: dagang
  ownerReferences:
  - apiVersion: flinkoperator.k8s.io/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: FlinkCluster
    name: flinkjobcluster-sample
    uid: ad2d622d-0ca3-11ea-950a-42010a8a0014
  ...
```

**Comment by functicons** [comment] 2019-11-21 21:20
But it is very strange, in your log, the observed cluster is nil, but the observed child resources still exist. This is unexpected, maybe it is due to your Kubernetes version.

I think I can improve the operator to explicitly delete the observed child resources if the cluster is gone.

**Comment by Mrart** [comment] 2019-11-22 03:17
My version is kube-apiserver:v1.16.2.

**Comment by Mrart** [comment] 2019-11-22 03:29
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-21T06:29:18Z"
  generation: 1
  labels:
    app: flink
    cluster: flinkjobcluster-sample-1
    component: jobmanager
  name: flinkjobcluster-sample-1-jobmanager
  namespace: default
  resourceVersion: "4802907"
  selfLink: /apis/apps/v1/namespaces/default/deployments/flinkjobcluster-sample-1-jobmanager
  uid: 1f972534-0a60-4f3b-b9f2-ce27c1418b92
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flink
      cluster: flinkjobcluster-sample-1
      component: jobmanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flink
        cluster: flinkjobcluster-sample-1
        component: jobmanager
    spec:
      containers:
      - args:
        - jobmanager
        env:
        - name: JOB_MANAGER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: jobmanager
              divisor: 1m
              resource: limits.cpu
        - name: JOB_MANAGER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: jobmanager
              divisor: 1Mi
              resource: limits.memory
        image: sloth-test0.dg.163.org/flink/flink:1.8.2
        imagePullPolicy: Always
        name: jobmanager
        ports:
        - containerPort: 6123
          name: rpc
          protocol: TCP
        - containerPort: 6124
          name: blob
          protocol: TCP
        - containerPort: 6125
          name: query
          protocol: TCP
        - containerPort: 8081
          name: ui
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/flink/conf
          name: flink-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: flinkjobcluster-sample-1-configmap
        name: flink-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-21T06:29:20Z"
    lastUpdateTime: "2019-11-21T06:29:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-21T06:29:18Z"
    lastUpdateTime: "2019-11-21T06:29:20Z"
    message: ReplicaSet "flinkjobcluster-sample-1-jobmanager-5848bdf766" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by functicons** [comment] 2019-11-22 03:40
That's weird, we set `ownerReferences` here https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/72f92a652b23070f06cf144fbcae49890700b81d/controllers/flinkcluster_converter.go#L200.

**Comment by Mrart** [comment] 2019-11-22 06:20
ownerReferences:
  - apiVersion: flinkoperator.k8s.io/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: FlinkCluster
    name: flinkjobcluster-sample
    uid: 7c901c12-ff08-4204-b46d-f7abbce4e7b7

**Comment by functicons** [comment] 2019-11-22 07:02
Why does it have ownerReferences now?

**Comment by Mrart** [comment] 2019-11-22 07:22
I don't know， It seems ‘ fortuitous’。

**Comment by functicons** [comment] 2019-11-23 20:18
Did you test with other versions of Kubernetes? 1.16 is pretty new, I suspect it has some problems.

**Comment by Mrart** [comment] 2019-12-03 12:47
@functicons  But I think it is now the problem about k8s。 when I use fabric8 k8s client delete It，It will Reproduce， the problem

**Comment by functicons** [comment] 2020-01-06 22:05
Is it related to fabric8 k8s client? Do you still see this problem?

**Comment by Mrart** [comment] 2020-01-07 07:54
I think it will relate to it

**Comment by Mrart** [comment] 2020-02-20 04:02
@functicons  I found this problem。 As I use fabric delete, It means not use "withPropagationPolicy("Foreground")" as default .
Then  I think we can use "extensions/v1beta1" version for deployment. As describe 
` For kinds in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 group versions, unless you specify otherwise, dependent objects are orphaned by default. In Kubernetes 1.9, for all kinds in the apps/v1 group version, dependent objects are deleted by default.`

**Comment by functicons** [comment] 2020-03-01 19:47
@Mrart can we close this issue? or do you want to update something?

**Closed** 2020-03-02 02:18 UTC
Labels: bug
